services:
  proxy:
    container_name: proxy-local
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/proxy/development/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./services/proxy/development/sites-enabled:/etc/nginx/sites-enabled:ro"
      - "./services/proxy/development/certificates:/var/www/dev.sts.com/certificates:ro"
      - "./images:/usr/share/nginx/html/images:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  maindb:
    container_name: main-db-local
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - main-db-data:/data/db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api_main:
    container_name: api-main-local
    build:
      context: ./services/api-main
      dockerfile: ./docker/Dockerfile.development
    environment:
      MAIN_DB_USERNAME: ${MAIN_DB_USERNAME}
      MAIN_DB_PWD: ${MAIN_DB_PWD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3001:3000"
    volumes:
      - "./services/api-main:/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ssr:
    container_name: ssr-local
    build:
      context: ./services/ssr
      dockerfile: ./docker/Dockerfile.development
    ports:
      - "3003:3000"
    environment:
      NODE_ENV: "development"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    volumes:
      - "./services/ssr:/app/"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  seeder:
    container_name: seeder
    image: node:18-alpine3.16
    environment:
      MAIN_DB_USERNAME: ${MAIN_DB_USERNAME}
      MAIN_DB_PWD: ${MAIN_DB_PWD}
    volumes:
      - ./tools/seeder/:/app

volumes:
  main-db-data:
