services:
  ticketing:
    container_name: ticketing-local
    build:
      context: ./services/ticketing
      dockerfile: ./docker/Dockerfile.development
    ports:
      - "3001:3000"
    # restart: unless-stopped
    environment:
      NODE_ENV: "development"
    volumes:
      - "./services/ticketing:/app/"
