export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  REGISTERED: 'REGISTERED',
  BANNED: 'BANNED',
};

export const USER_STATUSES = [
  USER_STATUS.ACTIVE,
  USER_STATUS.REGISTERED,
  USER_STATUS.BANNED,
];
