FROM node:18-alpine3.16

# Basic setup
WORKDIR /app
ENV NODE_ENV=development

# Install nestjs cli
RUN npm i -g @nestjs/cli@9.3.0

# Install dependencies first to utilize build cache
COPY package*.json ./
RUN npm install

# Copy the sourcecode
COPY . .

# Start the development server
CMD npm run start


