export const INTERNAL_TICKET_COLOR = '#FFD1DC';

export const TICKET_HISTORY_ENTRY_TYPE = {
  CREATED: 'CREATED',
  TITLE_CHANGED: 'TITLE_CHANGED',
  BODY_CHANGED: 'BODY_CHANGED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  DELETED: 'DELETED',
  ASSIGNEES_CHANGED: 'ASSIGNEES_CHANGED',
};
