import { ROLE } from '@/enums/roles';
import { defineMessages } from 'react-intl';

export const manageUsersMessages = defineMessages({
  pageTitle: {
    id: 'manage-users.page-title',
    defaultMessage: 'Manage Users | STS',
  },
  fullNameTableHeader: {
    id: 'manage-users.full-name-table-header',
    defaultMessage: 'Full Name',
  },
  roleTableHeader: {
    id: 'manage-users.role-table-header',
    defaultMessage: 'Role',
  },
  statusTableHeader: {
    id: 'manage-users.status-table-header',
    defaultMessage: 'Status',
  },
  aiAccessTableHeader: {
    id: 'manage-users.ai-access-table-header',
    defaultMessage: 'AI Access',
  },
  actionsTableHeader: {
    id: 'manage-users.actions-table-header',
    defaultMessage: 'Actions',
  },
  changeRoleTitle: {
    id: 'manage-users.change-role-title',
    defaultMessage: 'Change role',
  },
  changeStatusTitle: {
    id: 'manage-users.change-status-title',
    defaultMessage: 'Change status',
  },
  grantAIAccess: {
    id: 'manage-users.grant-ai-access',
    defaultMessage: 'Grant AI access',
  },
  revokeAIAccess: {
    id: 'manage-users.revoke-ai-access',
    defaultMessage: 'Revoke AI access',
  },
  changeRoleAreYouSure: {
    id: 'manage-users.change-role-are-you-sure',
    defaultMessage:
      'Are you sure you want to change {name} from {OldRole} to {NewRole}? ',
  },
  changeRoleWarning: {
    id: 'manage-users.change-role-wraning',
    defaultMessage:
      'This may expose user to info that was previously considered private for them. You also may not be able to undo this action yourself depending on your role.',
  },
  changeTo: {
    id: 'manage-users.change-to',
    defaultMessage: 'Change to {what}',
  },
  changeStatusAreYouSure: {
    id: 'manage-users.change-status-are-you-sure',
    defaultMessage:
      'Are you sure you want to change {name} from {OldStatus} to {NewStatus}? ',
  },
  changeStatusWarning: {
    id: 'manage-users.change-status-wraning',
    defaultMessage: 'This may enable or disable the user to use some services.',
  },
  createNewUserButtonText: {
    id: 'manage-users.create-new-user-button-text',
    defaultMessage: 'Create new user',
  },
});

export const cannotChangeRoleNotesMessages = defineMessages({
  [ROLE.CUSTOMER]: {
    id: 'manage-users.change-roles-customer-note',
    defaultMessage:
      'Customers cannot change their role for security reasons. If a customer became an agent please create a new account for them.',
  },
  default: {
    id: 'manage-users.change-roles-default-note',
    defaultMessage: 'No roles available for this type of user.',
  },
});

export const createUserMessages = defineMessages({
  pageTitle: {
    id: 'create-user.page-title',
    defaultMessage: 'Create User | STS',
  },
  createUserTitle: {
    id: 'create-user.create-user-title',
    defaultMessage: 'Create a new user',
  },
  createUserAlertText: {
    id: 'create-user.create-user-alert-text',
    defaultMessage:
      'This action will create a new inactive user in the system. You will be able to change their role and status later.',
  },
  createUserHeading: {
    id: 'create-user.create-user-heading',
    defaultMessage: 'Create a new user',
  },
  createUserCTA: {
    id: 'create-user.create-user-cta',
    defaultMessage: 'Create the user',
  },
  autoGenerated: {
    id: 'create-user.auto-generated',
    defaultMessage: 'auto-generated',
  },
  createUserSuccessText: {
    id: 'create-user.create-user-success-text',
    defaultMessage: 'You have successfully created the following user:',
  },
  theirPasswordHint: {
    id: 'create-user.their-password-hint',
    defaultMessage: 'Their password is the following:',
  },
  notifyThem: {
    id: 'create-user.notify-them',
    defaultMessage:
      'Please notify them about this account creation, and let them know that password change is suggested',
  },
});
