FROM python:3.9-slim
WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY app.py ./app.py
COPY api.py ./api.py

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install -r /app/requirements.txt


CMD ["streamlit", "run", "/app/app.py"]


